Repository NeuraLegion/cypress-har-generator, pull requests merged in 2024-09, with the labels that each got.

#443 build(deps-dev): bump jest from 28.1.3 to 29.7.0
  cypress/e2e/save-har.cy.ts
  package-lock.json
  package.json
Labels: Type: dependencies

#444 build(eslint): correct invalid configuration for `@typescript-eslint/member-ordering` rule
  .eslintrc.js
Labels: Type: tooling, Type: cleanup

#442 build(deps-dev): bump actions from 2 to 4 in /github/workflows
  .github/workflows/auto-build.yml
  .github/workflows/composite/npm/action.yml
  .github/workflows/coverage.yml
  .github/workflows/deploy.yml
  .github/workflows/release.yml
Labels: Type: dependencies

#446 chore(license): update licensing year
  LICENSE
  README.md
Labels: Type: documentation, Type: maintenance

#452 ci: update dependabot's configuration
  .github/dependabot.yml
Labels: Type: tooling

#454 build(deps-dev): bump devtools-protocol from 0.0.1138159 to 0.0.1352404
  package-lock.json
  src/cdp/DefaultNetwork.ts
Labels: Type: dependencies

#457 build(deps-dev): bump semantic-release from 19.0.5 to 24.1.0
  .github/workflows/auto-build.yml
  .github/workflows/coverage.yml
  package-lock.json
  package.json
Labels: Type: dependencies

#459 fix(deps): bump package versions to resolve vulnerabilities
  package-lock.json
Labels: Type: bug, Priority: high, Type: dependencies

#460 feat(plugin): make plugin a "no-op" in unsupported browsers
  src/Plugin.spec.ts
  src/Plugin.ts
Labels: Type: enhancement
